[package]
name = "laurel-redis"
description = "Laurel Common Redis"
version = "1.0.0"
edition = "2024"


[dependencies]
anyhow = "1"
tracing = "0.1"
fred = {version="10.1", features=["i-redis-json"]}
serde = { version = "1.0", features = ["derive"] }

