[server_config]
host = "0.0.0.0"
port = 8080

[log_config]
level = "info"
location = "logs"
prefix = "laurel-uc"
appender = "console" #console file all

[db_config]
host = "127.0.0.1"
port = 5432
user = "admin"
password = "admin"
database = "laurel_uc"
max_connections = 30
min_connections = 15
options = ""

[redis_config]
hosts = [{ host = "127.0.0.1", port = 6379 }]
db = 0

[api_config]
id_service = "http://127.0.0.1:18080"