[print_schema]
file = "src/schema/schema.rs"
filter = { except_tables = ["__diesel_schema_migrations"] }
import_types = ["diesel::sql_types::*"]
custom_type_derives = ["Debug", "Clone", "serde::Serialize", "serde::Deserialize"]

[migrations_directory]
dir = "migrations"